name: Build
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        registry: ghcr.io
        githubOrg: mcfearsome
        image: swiss-army-devops
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}
        addTimestamp: false
        addLatest: true
